name: go-web-app-CI

on:
  push:
    branches:
      - main
    paths-ignore:
      #- 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Go 1.22
          uses: actions/setup-go@v2
          with:
            go-version: 1.22
        
        - name: Build
          run: go build -o go-web-app 

        - name: Test
          run: go test ./...

    check-code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        #improve code quality, find potential bugs
        - name: Run golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.56.2

    docker-build-push:
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          
        - name: Docker Setup Buildx
          uses: docker/setup-buildx-action@v3.11.1
        
        - name: Docker Login
          uses: docker/login-action@v3.5.0
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            files: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

    update-tag-helm:
        runs-on: ubuntu-latest
        needs: docker-build-push
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.TOKEN }}
        
        - name: Update tag in Helm chart
          run: |
            sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

        - name: Commit and push changes
          run: |
            git config user.email "${{ secrets.email}}"
            git config user.name "nyilinhtut"
            git add helm/go-web-app-chart/values.yaml
            git commit -m "Update tag in Helm chart"
            git push



        
          
    

